@startuml diagrama-contexto-global

left to right direction
skinparam linetype polyline

state "SESION_CERRADA" as NoAuth
state "SISTEMA_DISPONIBLE" as Menu

state "MAQUINAS_ABIERTO" as ListMaquinas
state "MAQUINA_ABIERTO" as EditMaquina

state "PLAZAS_ABIERTO" as ListPlazas
state "PLAZA_ABIERTO" as EditPlaza

state "VENTAS_ABIERTO" as ListVentas
state "VENTA_ABIERTO" as EditVenta

state "REEMBOLSOS_ABIERTO" as ListReembolsos
state "REEMBOLSO_ABIERTO" as EditReembolso

state "CIERRES_ABIERTO" as ListCierres
state "CIERRE_ABIERTO" as EditCierre

state "USUARIOS_ABIERTO" as ListUsuarios
state "USUARIO_ABIERTO" as EditUsuario


[*] --> NoAuth

NoAuth --> Menu : iniciarSesion()
Menu --> NoAuth : cerrarSesion()

' Navegación desde el Menú Principal
Menu --> ListMaquinas: abrirMaquinas()
Menu --> ListPlazas: abrirPlazas()
Menu --> ListVentas: abrirVentas()
Menu --> ListCierres: abrirCierres()
Menu --> ListReembolsos: abrirReembolsos()
Menu --> ListUsuarios: abrirUsuarios()


'MÓDULO: MÁQUINAS (Gestión y Asignación de Personal)
ListMaquinas --> EditMaquina: registrarMaquina()
ListMaquinas --> EditMaquina: editarMaquina()
ListMaquinas --> ListMaquinas: eliminarMaquina()

EditMaquina --> EditMaquina: editarMaquina()
EditMaquina --> EditMaquina: asignarMotorarioAMaquina()
EditMaquina --> EditMaquina: desasignarMotorarioDeMaquina()
EditMaquina --> ListMaquinas: abrirMaquinas()


' MÓDULO: PLAZAS (Gestión y Asignación de Control de Motorarios)
ListPlazas --> EditPlaza: registrarPlaza()
ListPlazas --> EditPlaza: editarPlaza()
ListPlazas --> ListPlazas: eliminarPlaza()

EditPlaza --> EditPlaza: editarPlaza()
EditPlaza --> EditPlaza: asignarTaquilleroAPlaza()
EditPlaza --> EditPlaza: desasignarTaquilleroDePlaza()
EditPlaza --> EditPlaza: asignarMaquinaAPlaza()
EditPlaza --> EditPlaza: desasignarMaquinaDePlaza()
EditPlaza --> ListPlazas: abrirPlazas()


' MÓDULO: VENTAS (Integridad Contable)
ListVentas --> EditVenta: registrarVenta()
ListVentas -->  EditVenta: consultarVenta()

EditVenta --> ListVentas: anularVenta()
EditVenta --> ListVentas: abrirVentas()


' MÓDULO: REEMBOLSOS
ListReembolsos --> EditReembolso: solicitarReembolso()
ListReembolsos --> EditReembolso: revisarReembolso()

EditReembolso --> ListReembolsos: procesarReembolso()
EditReembolso --> ListReembolsos: abrirReembolsos()


' MÓDULO: CIERRES DE CAJA (Flujo de Auditoría)
' Declaración inicial (Taquillero)
ListCierres --> EditCierre: registrarCierreDeCaja()
' Auditoría/Revisión (Supervisor)
ListCierres --> EditCierre: revisarCierreDeCaja()
' Corrección de rechazo (Taquillero)
ListCierres --> EditCierre: editarCierreDeCaja()
' Guardar decisión (Aprobar/Devolver)
EditCierre --> ListCierres: procesarCierre()

EditCierre --> ListCierres: abrirCierres()


' MÓDULO: USUARIOS (Baja lógica integrada en Edición)
ListUsuarios --> EditUsuario: registrarUsuario()
ListUsuarios --> EditUsuario: editarUsuario()
ListUsuarios --> EditUsuario: consultarUsuario()

EditUsuario --> EditUsuario: editarUsuario()
EditUsuario --> ListUsuarios: abrirUsuarios()


' Retorno al Menú Principal
ListMaquinas --> Menu: completarGestion()
ListPlazas --> Menu : completarGestion()
ListVentas --> Menu : completarGestion()
ListCierres --> Menu: completarGestion()
ListReembolsos --> Menu: completarGestion()
ListUsuarios --> Menu: completarGestion()



@enduml