@startuml diagrama-contexto-global

left to right direction
skinparam linetype polyline

state "SESION_CERRADA" as NoAuth
state "SISTEMA_DISPONIBLE" as Menu

state "MAQUINAS_ABIERTO" as ListMaquinas
state "MAQUINA_ABIERTA" as EditMaquina

state "PLAZAS_ABIERTO" as ListPlazas
state "PLAZA_ABIERTA" as EditPlaza

state "USUARIOS_ABIERTO" as ListUsuarios
state "USUARIO_ABIERTO" as EditUsuario

state "REPORTES_ABIERTO" as ListReportes
state "REPORTE_ABIERTO" as EditReporte

state "CAJA_ABIERTA" as EditCaja

state "VENTAS_ABIERTO" as ListVentas
state "VENTA_ABIERTA" as EditVenta


[*] --> NoAuth

' Autenticación
NoAuth --> Menu : iniciarSesion()
Menu --> NoAuth : cerrarSesion()

' Navegación desde el Menú Principal
Menu --> ListMaquinas: abrirMaquinas()
Menu --> ListPlazas: abrirPlazas()
Menu --> ListUsuarios: abrirUsuarios()
Menu --> ListReportes: abrirReportes()
Menu --> EditCaja: abrirCaja()
Menu --> ListVentas: abrirVentas()


' MÓDULO: MÁQUINAS
ListMaquinas --> EditMaquina: consultarMaquina()
ListMaquinas --> EditMaquina: editarMaquina()
ListMaquinas --> EditMaquina: registrarMaquina()

ListMaquinas --> ListMaquinas: darDeBajaMaquina()
ListMaquinas --> ListMaquinas: reactivarMaquina()
ListMaquinas --> ListMaquinas: asignarMotorarioAMaquina()
ListMaquinas --> ListMaquinas: desasignarMotorarioDeMaquina()

EditMaquina --> EditMaquina: editarMaquina()
EditMaquina --> ListMaquinas: abrirMaquinas()


' MÓDULO: PLAZAS
ListPlazas --> EditPlaza: consultarPlaza()
ListPlazas --> EditPlaza: editarPlaza()
ListPlazas --> EditPlaza: registrarPlaza()

ListPlazas --> ListPlazas: darDeBajaPlaza()
ListPlazas --> ListPlazas: reactivarPlaza()
ListPlazas --> ListPlazas: asignarMaquinaAPlaza()
ListPlazas --> ListPlazas: desasignarMaquinaDePlaza()
ListPlazas --> ListPlazas: asignarTaquilleroAPlaza()
ListPlazas --> ListPlazas: desasignarTaquilleroDePlaza()

EditPlaza --> EditPlaza: editarPlaza()
EditPlaza --> ListPlazas: abrirPlazas()


' MÓDULO: USUARIOS
ListUsuarios --> EditUsuario: consultarUsuario()
ListUsuarios --> EditUsuario: editarUsuario()
ListUsuarios --> EditUsuario: crearUsuario()

ListUsuarios --> ListUsuarios: desactivarUsuario()
ListUsuarios --> ListUsuarios: reactivarUsuario()

EditUsuario --> EditUsuario: editarUsuario()
EditUsuario --> ListUsuarios: abrirUsuarios()


' MÓDULO: REPORTES DE MOTORARIO
ListReportes --> EditReporte: iniciarReporte()

EditReporte --> EditReporte: reportarTicketsRecibidos()
EditReporte --> ListReportes: finalizarReporte()


' MÓDULO: CAJA
EditCaja --> EditCaja: revisarCierreDeCaja()
EditCaja --> EditCaja: consolidarCierreDeCaja()


' MÓDULO: VENTAS
ListVentas --> EditVenta: registrarVenta()

ListVentas --> ListVentas: solicitarAnulacionVenta()
ListVentas --> ListVentas: anularVenta()
ListVentas --> ListVentas: autorizarReembolso()

EditVenta --> ListVentas: abrirVentas()


' Retorno al Menú Principal (completarGestion)
ListMaquinas --> Menu: completarGestion()
ListPlazas --> Menu: completarGestion()
ListUsuarios --> Menu: completarGestion()
ListReportes --> Menu: completarGestion()
EditCaja --> Menu: completarGestion()
ListVentas --> Menu: completarGestion()

@enduml