@startuml CU12_DarDeBajaPlaza

skinparam linetype polyline

state darDeBajaPlaza as "darDeBajaPlaza(plaza)" {

    state " " as SolicitandoConfirmacion
    state " " as ProcesandoBaja

    [*] -[#green]-> SolicitandoConfirmacion
    note on link
    <b>Supervisor</b> solicita dar de baja una plaza existente
    end note

    SolicitandoConfirmacion -[#green]-> ProcesandoBaja
    note on link
    <b>Sistema</b> presenta la ficha de la plaza y advierte que la baja
    suspenderá los vínculos con sus máquinas y taquilleros asignados
    • Permite solicitar confirmar baja
    • Permite solicitar cancelar operación
    end note

    ProcesandoBaja -[#green]-> [*]
    note on link
    <b>Supervisor</b> confirma la baja
    <b>Sistema</b> marca la plaza como inactiva, suspende los vínculos asignados y guarda cambios
    end note
}

darDeBajaPlaza -[#green]-> PLAZAS_ABIERTO
note on link
completarGestion()
end note

darDeBajaPlaza -[#blue]-> PLAZAS_ABIERTO
note on link
cancelar baja
end note

@enduml