@startuml CU23_DesasignarTaquilleroDePlaza

skinparam linetype polyline

state desasignarTaquilleroDePlaza as "desasignarTaquilleroDePlaza(plaza)" {

    state " " as SolicitandoConfirmacion
    state " " as ProcesandoDesasignacion

    [*] -[#green]-> SolicitandoConfirmacion
    note on link
    <b>Supervisor</b> solicita desasignar un taquillero de su plaza actual
    end note

    SolicitandoConfirmacion -[#green]-> ProcesandoDesasignacion
    note on link
    <b>Sistema</b> presenta la ficha del taquillero con su plaza asignada actual
    • Muestra advertencia de que el taquillero quedará sin plaza asignada
    • Permite solicitar confirmar desasignación
    • Permite solicitar cancelar operación
    end note

    ProcesandoDesasignacion -[#green]-> [*]
    note on link
    <b>Supervisor</b> confirma la desasignación
    <b>Sistema</b> desvincula el taquillero de su plaza actual, actualiza su estado a disponible y guarda cambios
    end note
}

desasignarTaquilleroDePlaza -[#green]-> PLAZAS_ABIERTO
note on link
completarGestion()
end note

desasignarTaquilleroDePlaza -[#blue]-> PLAZAS_ABIERTO
note on link
cancelar desasignación
end note

@enduml