@startuml CU03_ConsolidarCierreDeCaja

skinparam linetype polyline

state consolidarCierreDeCaja as "consolidarCierreDeCaja(cierre)" {

    state " " as RequiringConsolidation
    state " " as ProvidingSummary
    state " " as ValidatingData
    state c <<choice>>

    [*] -[#green]-> RequiringConsolidation
    note on link
    <b>Taquillero</b> solicita consolidar el cierre de caja del turno/día
    end note

    RequiringConsolidation -[#green]-> ProvidingSummary
    note on link
    <b>Sistema</b> presenta resumen del día (ventas, reembolsos y reportes de motorarios de solo lectura)
    • Permite modificar datos de ventas y añadir observaciones
    • Permite solicitar confirmar consolidación
    end note

    ProvidingSummary -[#green]-> ValidatingData
    note on link
    <b>Taquillero</b> confirma los datos introducidos y solicita guardar consolidación
    end note

    ValidatingData -[#green]-> c
    note on link
    <b>Sistema</b> valida los datos y observaciones introducidas
    end note

    c -[#red]-> ProvidingSummary
    note on link
    datos inválidos o incompletos
    end note

    c -[#green]-> [*]
    note on link
    datos válidos, cierre marcado como PENDIENTE_REVISION, notificado al Supervisor y guardado
    end note
}

consolidarCierreDeCaja -[#green]-> CAJA_ABIERTA
note on link
completarGestion()
end note

consolidarCierreDeCaja -[#blue]-> CAJA_ABIERTA
note on link
cancelar consolidación
end note

@enduml