@startuml DdCdU-supervisor-gestion-de-maquinas

left to right direction

actor "Supervisor" as supervisor

package "Módulo: Gestión de Máquinas" {
    usecase registrarMaquina as "registrarMaquina()"
    usecase consultarMaquina as "consultarMaquina()"
    usecase editarMaquina as "editarMaquina()"
    usecase darDeBajaMaquina as "darDeBajaMaquina()"
    usecase reactivarMaquina as "reactivarMaquina()"

    usecase asignarMotorarioAMaquina as "asignarMotorarioAMaquina()"
    usecase desasignarMotorarioDeMaquina as "desasignarMotorarioDeMaquina()"
}

supervisor --> registrarMaquina
supervisor --> consultarMaquina
supervisor --> editarMaquina
supervisor --> darDeBajaMaquina
supervisor --> reactivarMaquina

supervisor --> asignarMotorarioAMaquina
supervisor --> desasignarMotorarioDeMaquina

@enduml