@startuml DdCdU-supervisor-gestion-de-plazas

left to right direction

actor "Supervisor" as supervisor

package "Módulo: Gestión de Plazas" {
    usecase registrarPlaza as "registrarPlaza()"
    usecase consultarPlaza as "consultarPlaza()"
    usecase editarPlaza as "editarPlaza()"
    usecase darDeBajaPlaza as "darDeBajaPlaza()"
    usecase reactivarPlaza as "reactivarPlaza()"

    usecase asignarMaquinaAPlaza as "asignarMaquinaAPlaza()"
    usecase desasignarMaquinaDePlaza as "desasignarMaquinaDePlaza()"

    usecase asignarTaquilleroAPlaza as "asignarTaquilleroAPlaza()"
    usecase desasignarTaquilleroDePlaza as "desasignarTaquilleroDePlaza()"
}

supervisor --> registrarPlaza
supervisor --> consultarPlaza
supervisor --> editarPlaza
supervisor --> darDeBajaPlaza
supervisor --> reactivarPlaza

supervisor --> asignarMaquinaAPlaza
supervisor --> desasignarMaquinaDePlaza

supervisor --> asignarTaquilleroAPlaza
supervisor --> desasignarTaquilleroDePlaza

@enduml