@startuml DdCdU-motorario

left to right direction

actor "Motorario" as motorario

package "Módulo: Reporte de Tickets" {
    usecase iniciarReporte as "iniciarReporte()"
    usecase reportarTicketsRecibidos as "reportarTicketsRecibidos()"
    usecase finalizarReporte as "finalizarReporte()"
}

motorario --> iniciarReporte
motorario --> reportarTicketsRecibidos
motorario --> finalizarReporte

@enduml