@startuml DdCdU-supervisor-gestion-de-ventas

left to right direction

actor "Supervisor" as supervisor

package "Módulo: Gestión de Ventas y Caja" {
    usecase anularVenta as "anularVenta()"
    usecase autorizarReembolso as "autorizarReembolso()"
    usecase revisarCierreDeCaja as "revisarCierreDeCaja()"
    usecase consolidarCierreDeCaja as "consolidarCierreDeCaja()"
}

supervisor --> anularVenta
supervisor --> autorizarReembolso
supervisor --> revisarCierreDeCaja
supervisor --> consolidarCierreDeCaja

@enduml