  @startuml diagrama-modelo-del-dominio
  
  class Supervisor
  class Taquillero
  class Motorario
  
  class Maquina
  class Plaza
  class Venta
  class Ticket
  class CierreDeCaja
  class ReporteDeTickets
  
  Plaza o-- Maquina
  
  Maquina --> Motorario : asignada a
  Motorario --> ReporteDeTickets : genera
  Ticket --> Maquina : corresponde a
  ReporteDeTickets o-- Ticket
  
  Taquillero --> Plaza : asignado a
  Taquillero --> Venta : registra
  Venta *-- Ticket
  
  CierreDeCaja --> Venta : consolida/audita
  Taquillero --> CierreDeCaja : realiza
  Supervisor --> CierreDeCaja : revisa/consolida
  
  Supervisor --> Plaza : da de alta/baja
  Supervisor --> Maquina : da de alta/baja
  
  @enduml