@startuml CU18_ConsultarPlaza
title Consultar Plaza
skinparam nodesep 100
skinparam ranksep 100
skinparam linetype ortho
skinparam Padding 10

state PLAZAS_ABIERTO_INICIAL as "PLAZAS_ABIERTO"
state PLAZA_ABIERTA as "PLAZA_ABIERTA"
state PLAZAS_ABIERTO_FINAL as "PLAZAS_ABIERTO"

[*] -[#green]-> PLAZAS_ABIERTO_INICIAL

PLAZAS_ABIERTO_INICIAL -[#green]-> PLAZA_ABIERTA : consultarPlaza()
note left on link
    <b>Supervisor solicita</b> consultar el detalle
    de una plaza existente.
    <b>Sistema presenta</b> la ficha completa
    de la plaza.
end note

state PLAZA_ABIERTA {
    state VisualizacionPlaza as "Visualización de Plaza"

    [*] -[#green]-> VisualizacionPlaza
    note right of VisualizacionPlaza
        <b>Sistema muestra</b> los datos de la plaza:
        nombre, ciudad, estado y máquinas
        y taquilleros asignados.
        <b>Sistema permite solicitar</b> editar
        mediante editarPlaza().
    end note

    VisualizacionPlaza -[#green]-> [*]
}

PLAZA_ABIERTA -[#red]-> PLAZAS_ABIERTO_FINAL : cerrarPlaza()
note right on link
    <b>CERRAR:</b>
    <b>Supervisor solicita</b> salir de la ficha.
    <b>Sistema presenta</b> el listado de plazas.
end note

PLAZAS_ABIERTO_FINAL -[#blue]-> [*]

@enduml