@startuml DdCdU-taquillero

left to right direction

actor "Taquillero" as taquillero

package "Módulo: Gestión de Taquilla y Venta" {
    usecase registrarVenta as "registrarVenta()"
    usecase solicitarAnulacionVenta as "solicitarAnulacionVenta()"
    usecase declararCierreDeCaja as "declararCierreDeCaja()"
}

taquillero --> registrarVenta
taquillero --> declararCierreDeCaja

solicitarAnulacionVenta .> registrarVenta : <<extend>>

@enduml