@startuml diagrama-casos-uso-taquillero

left to right direction

package "Gestión De Taquilla y Venta" {

    actor "Taquillero" as taquillero

    usecase solicitarAnulacionVenta as "solicitarAnulacionVenta()"
    usecase consolidarCierreDeCaja as "consolidarCierreDeCaja()"
    usecase registrarVenta as "registrarVenta()"
 
}

taquillero --> solicitarAnulacionVenta
taquillero --> consolidarCierreDeCaja
taquillero --> registrarVenta


@enduml