@startuml DdCdU-administrador

left to right direction

actor "Administrador" as administrador

package "Módulo: Gestión de Usuarios" {
    usecase crearUsuario as "crearUsuario()"
    usecase consultarUsuario as "consultarUsuario()"
    usecase editarUsuario as "editarUsuario()"
    usecase desactivarUsuario as "desactivarUsuario()"
    usecase reactivarUsuario as "reactivarUsuario()"
}

administrador --> crearUsuario
administrador --> consultarUsuario
administrador --> editarUsuario
administrador --> desactivarUsuario
administrador --> reactivarUsuario

@enduml