@startuml CU17_AsignarMotorarioAMaquina

skinparam linetype polyline

state asignarMotorarioAMaquina as "asignarMotorarioAMaquina(motorario, maquina)" {

    state " " as RequiringSelection
    state " " as ProvidingConfirmation
    state c <<choice>>

    [*] -[#green]-> RequiringSelection
    note on link
    <b>Supervisor</b> solicita asignar un motorario a una máquina
    end note

    RequiringSelection -[#green]-> ProvidingConfirmation
    note on link
    <b>Sistema</b> presenta
    • lista de motorarios activos disponibles (sin máquina asignada)
    • lista de máquinas activas disponibles (sin motorario asignado)
    • opción para confirmar o cancelar la vinculación
    end note

    ProvidingConfirmation -[#green]-> c
    note on link
    <b>Supervisor</b> solicita
    • confirmar asignación
    • cancelar asignación
    end note

    c -[#red]-> [*]
    note on link
    Supervisor cancela
    end note

    c -[#green]-> [*]
    note on link
    asignación exitosa
    end note
}

asignarMotorarioAMaquina -[#green]-> MAQUINAS_ABIERTO
note on link
completarGestion()
end note

asignarMotorarioAMaquina -[#blue]-> MAQUINAS_ABIERTO
note on link
cancelar asignación
end note

@enduml