@startuml CU24_DesasignarMotorarioDeMaquina

skinparam linetype polyline

state desasignarMotorarioDeMaquina as "desasignarMotorarioDeMaquina(maquina)" {

    state " " as SolicitandoConfirmacion
    state " " as ProcesandoDesasignacion

    [*] -[#green]-> SolicitandoConfirmacion
    note on link
    <b>Supervisor</b> solicita desasignar motorario de su máquina actual
    end note

    SolicitandoConfirmacion -[#green]-> ProcesandoDesasignacion
    note on link
    <b>Sistema</b> presenta la ficha del motorario con su máquina asignada actual
    • Muestra advertencia de que el motorario quedará disponible sin máquina
    • Permite solicitar confirmar desasignación
    • Permite solicitar cancelar operación
    end note

    ProcesandoDesasignacion -[#green]-> [*]
    note on link
    <b>Supervisor</b> confirma la desasignación
    <b>Sistema</b> desvincula el motorario de la máquina, actualiza su estado a disponible y guarda cambios
    end note
}

desasignarMotorarioDeMaquina -[#green]-> MAQUINAS_ABIERTO
note on link
completarGestion()
end note

desasignarMotorarioDeMaquina -[#blue]-> MAQUINAS_ABIERTO
note on link
cancelar desasignación
end note

@enduml