@startuml CU13_RegistrarMaquina

skinparam linetype polyline

state registrarMaquina as "registrarMaquina()" {

    state " " as RequiringData
    state " " as ProvidingForm
    state " " as ValidatingData
    state c <<choice>>

    [*] -[#green]-> RequiringData
    note on link
    <b>Supervisor</b> solicita registrar una nueva máquina
    end note

    RequiringData -[#green]-> ProvidingForm
    note on link
    <b>Sistema</b> presenta el formulario de registro de máquina
    • Nombre, tipoRestriccion
    • Configuración de tipos de ticket (Niño / Adulto) y sus precios
    end note

    ProvidingForm -[#green]-> ValidatingData
    note on link
    <b>Supervisor</b> ingresa los datos y solicita guardar
    end note

    ValidatingData -[#green]-> c
    note on link
    <b>Sistema</b> valida los datos ingresados y que al menos un tipo de ticket esté definido
    end note

    c -[#red]-> ProvidingForm
    note on link
    datos inválidos o faltantes
    end note

    c -[#green]-> [*]
    note on link
    datos válidos, máquina registrada sin plaza asignada y guardada
    end note
}

registrarMaquina -[#green]-> MAQUINAS_ABIERTO
note on link
completarGestion()
end note

registrarMaquina -[#blue]-> MAQUINAS_ABIERTO
note on link
cancelar registro
end note

@enduml